// SPDX-License-Identifier: MIT OR Apache-2.0
//
// tools/sighash.test.mjs — the message a signature is over, against the
// vectors consensus itself is tested with.
//
//   node --test tools/sighash.test.mjs
//
// The spend rung claims ∇ s p ( ⌘ w ) and points a reader at the bytes behind
// ⌘. That is a promise the page can only keep if the serialization is right to
// the byte, and a preimage that is subtly wrong is worse than none at all: it
// would put math on a page whose whole claim is that the math can be checked,
// and a reader who tried to check it would conclude the chain was wrong rather
// than the book.
//
// So nothing here is reasoned about. The legacy digest is run against all 500
// cases in Bitcoin Core's own src/test/data/sighash.json — generated by the
// implementation consensus actually runs, and covering the shapes nobody would
// think to write down: SINGLE past the end of the outputs, an input index past
// the end, OP_CODESEPARATOR inside a scriptCode. BIP143 is run against the
// worked examples in the BIP, which print their preimages in full, including
// all six sighash flags over one input.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

import { parseTx, legacyPreimage, bip143Preimage, dsha256, compact,
         sighashOf, sighashName, v0KeyHashCode } from '../web/btc-sighash.js';

// Core writes a uint256 the way it prints one, which is backwards from the way
// it hashes one.
const reversed = (h) => (h.match(/../g) || []).reverse().join('');
// The two consensus bugs the legacy algorithm keeps rather than fixes: both
// digest as the number 1, and legacyPreimage returns null instead of inventing
// a serialization that was never hashed.
const ONE = reversed('01' + '00'.repeat(31));

test('the legacy digest matches Core on all 500 of its own vectors', async () => {
  const rows = JSON.parse(await readFile(new URL('./fixtures-sighash.json', import.meta.url), 'utf8'))
    .slice(1);   // the first row is the column legend
  assert.equal(rows.length, 500, 'the fixture lost or gained cases');
  for (const [raw, script, index, type, expected] of rows) {
    const preimage = legacyPreimage(parseTx(raw), index, script, type | 0);
    if (preimage === null) { assert.equal(expected, ONE, `${raw.slice(0, 16)}… is not the 1 case`); continue; }
    assert.equal(reversed(await dsha256(preimage)), expected,
      `index ${index}, type ${type}, tx ${raw.slice(0, 24)}…`);
  }
});

test('the two shapes that were never serialized are refused, not invented', () => {
  // Core's own vectors are generated from valid combinations and never reach
  // these, so they are built here. Both digest as the number 1 in consensus --
  // not because anything was hashed, but because an early return handed back a
  // uint256 and the bug is now the rule. A page that printed a preimage for
  // either would be showing bytes nobody ever hashed.
  const input = (txid, n) => `${txid.repeat(32)}0${n}000000` + '00' + 'ffffffff';
  const twoInOneOut = `01000000` + '02' + input('11', 0) + input('22', 1)
    + '01' + '0000000000000000' + '00' + '00000000';
  const tx = parseTx(twoInOneOut);
  assert.equal(tx.ins.length, 2);
  assert.equal(tx.outs.length, 1);
  // An input index past the end of the inputs.
  assert.equal(legacyPreimage(tx, 2, '51', 0x01), null);
  // …and SIGHASH_SINGLE naming an output that is not there.
  assert.equal(legacyPreimage(tx, 1, '51', 0x03), null);
  assert.ok(legacyPreimage(tx, 1, '51', 0x01), 'the same index under ALL is ordinary');
  assert.ok(legacyPreimage(tx, 0, '51', 0x03), 'and SINGLE at an index that has an output');
});

// ─── BIP143, from the BIP's own worked examples ──────────────────────────

const NATIVE_P2WPKH = {
  what: 'Native P2WPKH',
  raw: '0100000002fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f0000000000eeffffff'
     + 'ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff'
     + '02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac'
     + '9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac11000000',
  index: 1,
  code: v0KeyHashCode('1d0f172a0ecb48aee1be1f2687d2963ae33f71a1'),
  value: 600000000,                       // 6 BTC
  type: 0x01,
  preimage: '0100000096b827c8483d4e9b96712b6713a7b68d6e8003a781feba36c31143470b4efd37'
    + '52b0a642eea2fb7ae638c36f6252b6750293dbe574a806984b8e4d8548339a3b'
    + 'ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a01000000'
    + '1976a9141d0f172a0ecb48aee1be1f2687d2963ae33f71a188ac0046c32300000000ffffffff'
    + '863ef3e1a92afbfdb97f31ad0fc7683ee943e9abcf2501590ff8f6551f47e5e51100000001000000',
  sighash: 'c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670',
};

const P2SH_P2WPKH = {
  what: 'P2SH-P2WPKH',
  raw: '0100000001db6b1b20aa0fd7b23880be2ecbd4a98130974cf4748fb66092ac4d3ceb1a54770100000000feffffff'
     + '02b8b4eb0b000000001976a914a457b684d7f0d539a46a45bbc043f35b59d0d96388ac'
     + '0008af2f000000001976a914fd270b1ee6abcaea97fea7ad0402e8bd8ad6d77c88ac92040000',
  index: 0,
  code: v0KeyHashCode('79091972186c449eb1ded22b78e40d009bdf0089'),
  value: 1000000000,                      // 10 BTC
  type: 0x01,
  preimage: '01000000b0287b4a252ac05af83d2dcef00ba313af78a3e9c329afa216eb3aa2a7b4613a'
    + '18606b350cd8bf565266bc352f0caddcf01e8fa789dd8a15386327cf8cabe198'
    + 'db6b1b20aa0fd7b23880be2ecbd4a98130974cf4748fb66092ac4d3ceb1a547701000000'
    + '1976a91479091972186c449eb1ded22b78e40d009bdf008988ac00ca9a3b00000000feffffff'
    + 'de984f44532e2173ca0d64314fcefe6d30da6f8cf27bafa706da61df8a226c839204000001000000',
};

// One input, one scriptCode, six flags — which is the whole of what a sighash
// type does, laid out side by side. Read the preimages down the column and the
// zeroed fields are the freedoms each flag grants.
const SIX_FLAGS = {
  raw: '010000000136641869ca081e70f394c6948e8af409e18b619df2ed74aa106c1ca29787b96e0100000000ffffffff'
     + '0200e9a435000000001976a914389ffce9cd9ae88dcc0631e88a821ffdbe9bfe2688ac'
     + 'c0832f05000000001976a9147480a33f950689af511e6e84c138dbbd3c3ee41588ac00000000',
  index: 0,
  value: 987654321,                       // 9.87654321 BTC
  code: '56210307b8ae49ac90a048e9b53357a2354b3334e9c8bee813ecb98e99a7e07e8c3ba3'
    + '2103b28f0c28bfab54554ae8c658ac5c3e0ce6e79ad336331f78c428dd43eea8449b'
    + '21034b8113d703413d57761b8b9781957b8c0ac1dfe69f492580ca4195f50376ba4a'
    + '21033400f6afecb833092a9a21cfdf1ed1376e58c5d1f47de74683123987e967a8f4'
    + '2103a6d48b1131e94ba04d9737d61acdaa1322008af9602b3b14862c07a1789aac16'
    + '2102d8b661b0b3302ee2f162b09e07a55ad5dfbe673a9f01d9f0c19617681024306b56ae',
};
const HEAD = '0100000074afdc312af5183c4198a40ca3c1a275b485496dd3929bca388c4b5e31f7aaa0';
const ZERO = '00'.repeat(32);
const OUTPOINT = '36641869ca081e70f394c6948e8af409e18b619df2ed74aa106c1ca29787b96e01000000';
const MID = `cf${SIX_FLAGS.code}b168de3a00000000ffffffff`;
const ALL_OUTS = 'bc4d309071414bed932f98832b27b4d76dad7e6c1346f487a8fdbb8eb90307cc';
const ONE_OUT = '9efe0c13a6b16c14a41b04ebe6a63f419bdacb2f8705b494a43063ca3cd4f708';
const SEQS = '3bb13029ce7b1f559ef5e747fcac439f1455a2ec7c5f09b72290795e70665044';
const FLAGS = [
  [0x01, `${HEAD}${SEQS}${OUTPOINT}${MID}${ALL_OUTS}0000000001000000`],
  [0x02, `${HEAD}${ZERO}${OUTPOINT}${MID}${ZERO}0000000002000000`],
  [0x03, `${HEAD}${ZERO}${OUTPOINT}${MID}${ONE_OUT}0000000003000000`],
  [0x81, `01000000${ZERO}${ZERO}${OUTPOINT}${MID}${ALL_OUTS}0000000081000000`],
  [0x82, `01000000${ZERO}${ZERO}${OUTPOINT}${MID}${ZERO}0000000082000000`],
  [0x83, `01000000${ZERO}${ZERO}${OUTPOINT}${MID}${ONE_OUT}0000000083000000`],
];

test('BIP143 writes the preimages the BIP prints', async () => {
  for (const v of [NATIVE_P2WPKH, P2SH_P2WPKH]) {
    const got = await bip143Preimage(parseTx(v.raw), v.index, v.code, v.value, v.type);
    assert.equal(got, v.preimage, v.what);
    if (v.sighash) assert.equal(await dsha256(got), v.sighash, `${v.what}: the digest`);
  }
  // The amount really is in there, which is the whole reason BIP143 exists: a
  // legacy preimage of the same input commits to no value at all.
  const amount = '0046c32300000000';
  assert.ok(NATIVE_P2WPKH.preimage.includes(amount), 'six bitcoin, eight bytes, little endian');
  const legacy = legacyPreimage(parseTx(NATIVE_P2WPKH.raw), 1, NATIVE_P2WPKH.code, 1);
  assert.ok(!legacy.includes(amount), 'and the algorithm it replaced could not say it');
});

test('every sighash flag zeroes exactly what it frees', async () => {
  const tx = parseTx(SIX_FLAGS.raw);
  for (const [type, expected] of FLAGS) {
    const got = await bip143Preimage(tx, SIX_FLAGS.index, SIX_FLAGS.code, SIX_FLAGS.value, type);
    assert.equal(got, expected, sighashName(type));
  }
  // …and the field each flag lets go is readable off the preimage itself,
  // which is the reason a page sets the preimage rather than the digest.
  const of = (type) => FLAGS.find(([t]) => t === type)[1];
  assert.ok(of(0x02).includes(`${ZERO}0000000002000000`), 'NONE signs no output');
  assert.ok(of(0x81).startsWith(`01000000${ZERO}${ZERO}`), 'ANYONECANPAY signs no other input');
  assert.notEqual(of(0x03).slice(-40), of(0x01).slice(-40), 'SINGLE signs one output, not all');
});

test('a signature carries its own flag, and says which', () => {
  const der = '3044' + '02'.repeat(34) + '01';
  assert.equal(sighashOf(der), 0x01);
  assert.equal(sighashName(sighashOf(der)), 'ALL');
  assert.equal(sighashName(0x83), 'SINGLE|ANYONECANPAY');
  // A 64-byte Schnorr signature writes its flag by leaving it out: the default
  // is ALL, and a byte would only be there to say something else.
  assert.equal(sighashOf('ab'.repeat(64)), 0x00);
  assert.equal(sighashOf('ab'.repeat(64) + '03'), 0x03, 'and 65 bytes is that byte');
});

test('the compact size is Bitcoin’s, not a varint', () => {
  // Every length in both preimages runs through this, so its boundaries are
  // worth pinning: a script of 253 bytes serializes differently from one of 252.
  assert.equal(compact(0), '00');
  assert.equal(compact(252), 'fc');
  assert.equal(compact(253), 'fdfd00');
  assert.equal(compact(0xffff), 'fdffff');
  assert.equal(compact(0x10000), 'fe00000100');
  assert.equal(compact(0xffffffff), 'feffffffff');
  assert.equal(compact(0x100000000), 'ff0000000001000000');
});

test('a transaction is read back exactly as it was written', async () => {
  // The parse has to be lossless over the fields a digest commits to, and the
  // 500-vector run above would catch most drift — but a segwit transaction
  // never appears there, and its marker and flag are exactly what a digest
  // must NOT see.
  const signed = '01000000000102fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f'
    + '00000000494830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cdd30be'
    + '022040529b194ba3f9281a99f2b1c0a19c0489bc22ede944ccf4ecbab4cc618ef3ed01eeffffff'
    + 'ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff'
    + '02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac'
    + '9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac0002'
    + '47304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a'
    + '0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee01'
    + '21025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee635711000000';
  const tx = parseTx(signed);
  assert.equal(tx.segwit, true);
  assert.equal(tx.ins.length, 2);
  assert.equal(tx.outs.length, 2);
  assert.equal(tx.locktime, '11000000');
  assert.deepEqual(tx.ins[1].witness.length, 2, 'the witness is read, and then not signed over');
  // The digest over the SIGNED transaction is the one the BIP prints for the
  // unsigned one: a witness changes nothing a signature covers, which is what
  // segregating it means.
  const got = await bip143Preimage(tx, 1, NATIVE_P2WPKH.code, NATIVE_P2WPKH.value, 1);
  assert.equal(got, NATIVE_P2WPKH.preimage);
});

test('the algorithm is chosen by the output, not by the spend', async () => {
  const { messageOf } = await import('../web/btc-sighash.js');
  const signed = '01000000000102fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f'
    + '00000000494830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cdd30be'
    + '022040529b194ba3f9281a99f2b1c0a19c0489bc22ede944ccf4ecbab4cc618ef3ed01eeffffff'
    + 'ef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff'
    + '02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac'
    + '9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac0002'
    + '47304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a'
    + '0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee01'
    + '21025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee635711000000';
  // Input 1 opened a v0 key-hash output, so it signed under BIP143 — and the
  // scriptCode is derived from the program's own datum, never read off the
  // spend. The witness and the sighash flag come off the input itself.
  const v0 = await messageOf({ script: '00141d0f172a0ecb48aee1be1f2687d2963ae33f71a1',
    raw: signed, index: 1, value: 600000000 });
  assert.equal(v0.algorithm, 'BIP143');
  assert.equal(v0.type, 0x01);
  assert.equal(v0.scriptCode, v0KeyHashCode('1d0f172a0ecb48aee1be1f2687d2963ae33f71a1'));
  assert.equal(v0.preimage, NATIVE_P2WPKH.preimage);
  assert.equal(v0.digest, NATIVE_P2WPKH.sighash);
  // Input 0 of the very same transaction opened a P2PK output, so it signed
  // under the legacy digest. One transaction, two algorithms — which is why the
  // choice is made from the output and not from the spend.
  const legacy = await messageOf({ script: '2103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432ac',
    raw: signed, index: 0, value: 625000000,
    scriptsig: '4830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cdd30be'
      + '022040529b194ba3f9281a99f2b1c0a19c0489bc22ede944ccf4ecbab4cc618ef3ed01' });
  assert.equal(legacy.algorithm, 'legacy');
  assert.equal(legacy.type, 0x01);
  assert.equal(legacy.preimage,
    legacyPreimage(parseTx(signed), 0, '2103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432ac', 1));
  // …and the amount is in one and not the other, which the fields say in words.
  assert.ok(v0.fields.some(([name]) => name === 'amount'));
  assert.ok(legacy.fields.some(([name]) => name === '(no amount)'));

  // Taproot's digest is BIP341's and is not written here, so it is not claimed.
  assert.equal(await messageOf({ script: '5120' + 'ab'.repeat(32), raw: signed, index: 1, value: 1 }), null,
    'a message this cannot serialize is named as unknown, not guessed');
  // BIP143 signs the amount, so without one there is no message to write.
  assert.equal(await messageOf({ script: '00141d0f172a0ecb48aee1be1f2687d2963ae33f71a1',
    raw: signed, index: 1, value: null }), null);
});

test('a real signature verifies against the preimage this writes', async () => {
  // The end of the argument. Every test above compares bytes against bytes
  // somebody else wrote down; this one asks secp256k1. If the serialization
  // were wrong in any field, in any byte, the digest would be a different
  // number and this would fail — which is the same check a node performs, and
  // the same one a reader with the footnote in front of them can perform.
  const crypto = await import('node:crypto');
  const preimage = await bip143Preimage(parseTx(NATIVE_P2WPKH.raw), NATIVE_P2WPKH.index,
    NATIVE_P2WPKH.code, NATIVE_P2WPKH.value, NATIVE_P2WPKH.type);
  // The key and the signature are the BIP's, printed beside the transaction.
  const pubkey = '025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357';
  const sig = '304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a'
    + '0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee';
  // A compressed point, wrapped in the SPKI the platform wants: the algorithm
  // is ecPublicKey over secp256k1, and the point follows.
  const spki = Buffer.concat([Buffer.from('3036301006072a8648ce3d020106052b8104000a032200', 'hex'),
    Buffer.from(pubkey, 'hex')]);
  const key = crypto.createPublicKey({ key: spki, format: 'der', type: 'spki' });
  // Bitcoin signs the double hash, so one SHA-256 is taken here and the verifier
  // takes the other — which is what "ECDSA over dSHA256" means when a library
  // only offers you the outer one.
  const once = crypto.createHash('sha256').update(Buffer.from(preimage, 'hex')).digest();
  assert.equal(crypto.verify('sha256', once, key, Buffer.from(sig, 'hex')), true,
    'the signature does not verify — the preimage is wrong somewhere');
  // …and it is not verifying just anything: one byte moved, and it fails.
  const bent = preimage.slice(0, 8) + (preimage[8] === '0' ? '1' : '0') + preimage.slice(9);
  const bentOnce = crypto.createHash('sha256').update(Buffer.from(bent, 'hex')).digest();
  assert.equal(crypto.verify('sha256', bentOnce, key, Buffer.from(sig, 'hex')), false);
});
