// SPDX-License-Identifier: MIT OR Apache-2.0
//
// btc-sighash.js — the message a signature is over, serialized so a reader can
// hash it themselves.
//
// A spend rung says ∇ s p ( ⌘ w ): this signature, under this key, over this
// message. The first two are on the page already — they are what the input
// carried, quoted and cited. The third was a mark with nothing behind it, and
// a demand nobody can evaluate is a demand nobody can check. This module is
// what puts something behind it.
//
// What it produces is the PREIMAGE, not the digest: the bytes that go into the
// hash, in order, with every field nameable. The digest is one dSHA256 away and
// this module will take it, but the preimage is the thing worth setting on a
// page — a reader who has it can hash it in one line and compare, and a reader
// who reads it can see exactly what a signature does and does not commit to.
// The digest alone would only be a number to be believed.
//
// Two algorithms, because Bitcoin has had two, and the difference between them
// is visible in the shape of what comes out:
//
//   legacy   the whole transaction, with every scriptSig blanked but the one
//            being signed, that one replaced by the scriptCode — so the amount
//            being spent is nowhere in it, which is the hole BIP143 was written
//            to close
//   BIP143   fixed fields and three sub-hashes, the input's own value among
//            them, so a signer who is told a value and lied to signs nothing
//            that verifies
//
// Both are checked against published vectors rather than reasoned about: Core's
// own sighash.json (500 legacy cases, generated by the implementation consensus
// actually runs) and BIP143's worked examples, which print their preimages in
// full. See tools/sighash.test.mjs. Nothing here is trusted because it looks
// right — a preimage that is subtly wrong would put false math on a page whose
// whole claim is that the math can be checked.

// ─── bytes ───────────────────────────────────────────────────────────────

const hex = (bytes) => bytes.map((b) => b.toString(16).padStart(2, '0')).join('');
const bytesOf = (h) => (String(h).match(/../g) || []).map((b) => parseInt(b, 16));

// Little-endian integers, which is how every count and amount rides on the
// wire. BigInt for the 8-byte ones: a satoshi amount passes 2^53 at 90,000 BTC,
// and this is a book about exact numbers.
const le = (n, width) => {
  let v = BigInt(n), out = '';
  for (let i = 0; i < width; i++) { out += Number(v & 0xffn).toString(16).padStart(2, '0'); v >>= 8n; }
  return out;
};

// Bitcoin's compact size, which is not a varint anywhere else: one byte under
// 0xfd, then a marker and 2, 4 or 8 little-endian bytes.
export const compact = (n) => {
  const v = Number(n);
  if (v < 0xfd) return le(v, 1);
  if (v <= 0xffff) return 'fd' + le(v, 2);
  if (v <= 0xffffffff) return 'fe' + le(v, 4);
  return 'ff' + le(v, 8);
};

// A script as it is serialized inside a CTxOut: its length, then its bytes.
const withLength = (script) => compact(script.length / 2) + script;

// The one hash Bitcoin means when it says "hash": SHA-256, twice. WebCrypto is
// async and there is no synchronous digest in a browser, so everything above
// this line is a string and everything that hashes is a promise.
export async function dsha256(h) {
  const once = await crypto.subtle.digest('SHA-256', new Uint8Array(bytesOf(h)));
  const twice = await crypto.subtle.digest('SHA-256', once);
  return hex([...new Uint8Array(twice)]);
}

// ─── reading a transaction off the wire ──────────────────────────────────
//
// Enough of one to sign over: the fields a digest commits to, in the order it
// commits to them. Segwit's marker and flag are read and dropped — a witness is
// never in either digest, which is the whole of what "segregated" means here.
export function parseTx(raw) {
  const b = bytesOf(raw);
  let i = 0;
  const take = (n) => { const s = hex(b.slice(i, i + n)); i += n; return s; };
  const u32 = () => { const s = take(4); return s; };
  const size = () => {
    const first = b[i++];
    if (first < 0xfd) return first;
    const n = first === 0xfd ? 2 : first === 0xfe ? 4 : 8;
    const s = take(n);
    return Number(BigInt('0x' + (s.match(/../g) || []).reverse().join('')));
  };
  const version = u32();
  let segwit = false;
  if (b[i] === 0x00 && b[i + 1] === 0x01) { segwit = true; i += 2; }
  const ins = [];
  const nIn = size();
  for (let n = 0; n < nIn; n++) {
    const txid = take(32), vout = take(4);
    const script = take(size());
    ins.push({ txid, vout, script, sequence: take(4) });
  }
  const outs = [];
  const nOut = size();
  for (let n = 0; n < nOut; n++) {
    const value = take(8);
    outs.push({ value, script: take(size()) });
  }
  if (segwit) {
    for (let n = 0; n < nIn; n++) {
      const items = [];
      const count = size();
      for (let k = 0; k < count; k++) items.push(take(size()));
      ins[n].witness = items;
    }
  }
  return { version, ins, outs, locktime: take(4), segwit };
}

// ─── sighash flags ───────────────────────────────────────────────────────

export const SIGHASH_ALL = 0x01, SIGHASH_NONE = 0x02, SIGHASH_SINGLE = 0x03;
export const SIGHASH_ANYONECANPAY = 0x80;
const base = (type) => type & 0x1f;
const anyone = (type) => Boolean(type & SIGHASH_ANYONECANPAY);

// What a flag is called, for the page that has to say it. The names are
// consensus's own; the reading beside each is what it costs.
export function sighashName(type) {
  const names = { [SIGHASH_ALL]: 'ALL', [SIGHASH_NONE]: 'NONE', [SIGHASH_SINGLE]: 'SINGLE' };
  const b = names[base(type)] ?? `0x${base(type).toString(16)}`;
  return anyone(type) ? `${b}|ANYONECANPAY` : b;
}

// The flag a signature carries, which is its last byte — DER for ECDSA, and for
// Schnorr a 65th byte that is only there when the flag is not the default.
export function sighashOf(sig) {
  const n = sig.length / 2;
  if (n === 64) return 0x00;                      // BIP341's default, written by omission
  return parseInt(sig.slice(-2), 16);
}

// ─── the legacy digest ───────────────────────────────────────────────────
//
// Everything before segwit, and still every P2PK, P2PKH, bare multisig and P2SH
// spend. The transaction is serialized again with one input's scriptSig
// replaced by the scriptCode and every other input's blanked, then the sighash
// type is appended as four little-endian bytes and the whole is hashed twice.
//
// The two shapes that are not a serialization at all are consensus's own bugs,
// kept because the chain is full of them: an input index past the end, and
// SIGHASH_SINGLE with no output at that index, both digest as the number 1
// rather than failing. A caller gets null and should say so rather than print a
// preimage that was never hashed.
export function legacyPreimage(tx, nIn, scriptCode, type) {
  if (nIn >= tx.ins.length) return null;
  if (base(type) === SIGHASH_SINGLE && nIn >= tx.outs.length) return null;
  // OP_CODESEPARATOR is struck from the scriptCode wherever it stands. (The
  // FindAndDelete of the signature itself is not done here: it can only matter
  // where a signature was pushed by the scriptCode, which no standard form
  // does, and guessing at it would be worse than declining.)
  const code = (scriptCode.match(/../g) || []).filter((b) => b !== 'ab').join('');
  const one = anyone(type);
  const ins = one ? [tx.ins[nIn]] : tx.ins;
  const body = ins.map((input, k) => {
    const idx = one ? nIn : k;
    const script = idx === nIn ? withLength(code) : compact(0);
    // NONE and SINGLE free every other input's sequence, which is what lets one
    // signer's timelock be rewritten by another's.
    const seq = idx !== nIn && (base(type) === SIGHASH_NONE || base(type) === SIGHASH_SINGLE)
      ? le(0, 4) : input.sequence;
    return input.txid + input.vout + script + seq;
  }).join('');
  const outs = base(type) === SIGHASH_NONE ? []
    : base(type) === SIGHASH_SINGLE ? tx.outs.slice(0, nIn + 1)
    : tx.outs;
  const outBody = outs.map((out, k) => (base(type) === SIGHASH_SINGLE && k !== nIn
    // A blanked output: value −1, and no script. Signed over, and worth
    // nothing to anyone.
    ? 'ffffffffffffffff' + compact(0)
    : out.value + withLength(out.script))).join('');
  return tx.version + compact(ins.length) + body
    + compact(outs.length) + outBody + tx.locktime + le(type, 4);
}

// ─── the BIP143 digest ───────────────────────────────────────────────────
//
// Segwit v0, and the fix that made it worth having: the value being spent is in
// the preimage, so a signer told the wrong amount produces a signature that
// verifies against nothing. The rest of the change is arithmetic — three
// sub-hashes over the inputs and outputs, reusable across every input of a
// transaction, which turns a quadratic verification cost into a linear one.
export async function bip143Preimage(tx, nIn, scriptCode, value, type) {
  const zero = '00'.repeat(32);
  const hashPrevouts = anyone(type) ? zero
    : await dsha256(tx.ins.map((i) => i.txid + i.vout).join(''));
  const hashSequence = anyone(type) || base(type) === SIGHASH_SINGLE || base(type) === SIGHASH_NONE
    ? zero : await dsha256(tx.ins.map((i) => i.sequence).join(''));
  const out = (o) => o.value + withLength(o.script);
  const hashOutputs = base(type) !== SIGHASH_SINGLE && base(type) !== SIGHASH_NONE
    ? await dsha256(tx.outs.map(out).join(''))
    : base(type) === SIGHASH_SINGLE && nIn < tx.outs.length
      ? await dsha256(out(tx.outs[nIn])) : zero;
  const input = tx.ins[nIn];
  return tx.version + hashPrevouts + hashSequence + input.txid + input.vout
    + withLength(scriptCode) + le(value, 8) + input.sequence
    + hashOutputs + tx.locktime + le(type, 4);
}

// The scriptCode a v0 input signs under. For a key-hash program it is the P2PKH
// template consensus builds from the program's own datum — the same script the
// term writes in its ( ) — and for a script-hash program it is the witness
// script the spend revealed.
export const v0KeyHashCode = (h160) => `76a914${h160}88ac`;

// ─── the fields, named ───────────────────────────────────────────────────
//
// A preimage set as one run of hex is a thing to be believed, not read. What a
// page wants is the same bytes cut at the joints, each piece named — so a
// reader can see that the amount is in there, or that the outputs are not.
export function bip143Fields(tx, nIn, scriptCode, value, type, parts) {
  const input = tx.ins[nIn];
  return [
    ['nVersion', tx.version, 'the transaction’s version, four bytes'],
    ['hashPrevouts', parts.hashPrevouts, anyone(type)
      ? 'zero — ANYONECANPAY signs no other input, so any of them may be added or dropped'
      : 'every input’s outpoint, hashed: which coins this transaction spends'],
    ['hashSequence', parts.hashSequence, parts.hashSequence === '00'.repeat(32)
      ? 'zero — this flag leaves every other input’s sequence free to be rewritten'
      : 'every input’s nSequence, hashed'],
    ['outpoint', input.txid + input.vout, 'the coin this input spends, named as the chain names it'],
    ['scriptCode', withLength(scriptCode), 'the script this signature is made under'],
    ['amount', le(value, 8), 'what the coin is worth — the field legacy signing had no place for'],
    ['nSequence', input.sequence, 'this input’s own sequence'],
    ['hashOutputs', parts.hashOutputs, base(type) === SIGHASH_NONE
      ? 'zero — NONE signs no output at all, so where the value goes is not committed to'
      : base(type) === SIGHASH_SINGLE ? 'the one output at this input’s index, hashed'
      : 'every output, hashed: the amounts and where they go'],
    ['nLockTime', tx.locktime, 'the earliest the transaction may be mined'],
    ['nHashType', le(type, 4), `${sighashName(type)} — which of the above the signature covers`],
  ];
}

// ─── which message, for which spend ──────────────────────────────────────
//
// The algorithm is chosen by the output being opened, not by the transaction
// doing the opening — which is the whole reason a spend rung can name a message
// at all. A v0 program signs under BIP143; everything before it signs under the
// legacy digest; and a P2SH output that wrapped a v0 program signs under BIP143
// too, since what the redeem script revealed is a witness program like any
// other.
//
// Null where the message cannot be named rather than a guess at one: taproot,
// whose digest is BIP341's and is not written here, and any shape whose
// scriptCode this cannot say. A ⌘ … on the page is the honest form of "not
// known", and it is better than bytes a reader would hash and find wrong.
const V0_KEYHASH = /^0014([0-9a-f]{40})$/;
const V0_SCRIPTHASH = /^0020[0-9a-f]{64}$/;

// The last push of a scriptSig, which is the redeem script a P2SH spend
// revealed. Read off the bytes rather than the term, because the term of the
// OUTPUT is a hash and knows nothing about it.
function lastPush(scriptsig) {
  const b = bytesOf(scriptsig);
  let i = 0, last = null;
  while (i < b.length) {
    const op = b[i++];
    let n = null;
    if (op >= 0x01 && op <= 0x4b) n = op;
    else if (op === 0x4c) n = b[i++];
    else if (op === 0x4d) { n = b[i] | (b[i + 1] << 8); i += 2; }
    else if (op === 0x4e) { n = b[i] | (b[i + 1] << 8) | (b[i + 2] << 16) | (b[i + 3] << 24); i += 4; }
    if (n === null) continue;                       // an opcode, not a push
    if (i + n > b.length) return null;
    last = hex(b.slice(i, i + n));
    i += n;
  }
  return last;
}

export async function messageOf({ script, raw, index, value, items = [], scriptsig = null }) {
  let tx;
  try { tx = parseTx(raw); } catch { return null; }
  if (!tx || index >= tx.ins.length) return null;
  const witness = items.length ? items : (tx.ins[index].witness || []);
  // A P2SH output hands its own reading over to what the spend revealed: a
  // wrapped witness program signs as that program, and anything else signs
  // legacy under the redeem script itself.
  let program = String(script).toLowerCase();
  let redeem = null;
  if (/^a914[0-9a-f]{40}87$/.test(program) && scriptsig) {
    redeem = lastPush(scriptsig);
    if (redeem && (V0_KEYHASH.test(redeem) || V0_SCRIPTHASH.test(redeem))) program = redeem;
  }
  // Taproot is BIP341's digest, which is a different serialization over a
  // different set of inputs. Not written here, so not claimed.
  if (/^5120[0-9a-f]{64}$/.test(program)) return null;

  const keyhash = V0_KEYHASH.exec(program);
  if (keyhash || V0_SCRIPTHASH.test(program)) {
    if (value == null) return null;                 // BIP143 signs the amount; without it there is no message
    const sig = witness[0];
    if (!sig) return null;
    const type = sighashOf(sig);
    const code = keyhash ? v0KeyHashCode(keyhash[1]) : witness[witness.length - 1];
    if (!code) return null;
    const preimage = await bip143Preimage(tx, index, code, value, type);
    const parts = await bip143Parts(tx, index, type);
    return { algorithm: 'BIP143', why: 'a version 0 witness program', preimage, type,
      digest: await dsha256(preimage), scriptCode: code,
      fields: bip143Fields(tx, index, code, value, type, parts) };
  }
  // Everything else is the legacy digest, under the output's own script -- or,
  // for a P2SH spend, under the redeem script the input revealed.
  const code = redeem ?? program;
  const sig = witness[0] ?? (scriptsig ? firstPush(scriptsig) : null);
  if (!sig) return null;
  const type = sighashOf(sig);
  const preimage = legacyPreimage(tx, index, code, type);
  if (!preimage) return null;
  return { algorithm: 'legacy', why: 'an output written before segwit', preimage, type,
    digest: await dsha256(preimage), scriptCode: code,
    fields: legacyFields(tx, index, code, type) };
}

// The first push of a scriptSig, which is where a legacy spend puts its
// signature -- P2PKH's s p, P2SH's own arguments, multisig's after its ⓪.
function firstPush(scriptsig) {
  const b = bytesOf(scriptsig);
  if (!b.length) return null;
  const op = b[0];
  if (op < 0x01 || op > 0x4b || 1 + op > b.length) return null;
  return hex(b.slice(1, 1 + op));
}

// The three sub-hashes, kept so the fields can be named without hashing twice.
async function bip143Parts(tx, nIn, type) {
  const zero = '00'.repeat(32);
  const out = (o) => o.value + withLength(o.script);
  return {
    hashPrevouts: anyone(type) ? zero : await dsha256(tx.ins.map((i) => i.txid + i.vout).join('')),
    hashSequence: anyone(type) || base(type) === SIGHASH_SINGLE || base(type) === SIGHASH_NONE
      ? zero : await dsha256(tx.ins.map((i) => i.sequence).join('')),
    hashOutputs: base(type) !== SIGHASH_SINGLE && base(type) !== SIGHASH_NONE
      ? await dsha256(tx.outs.map(out).join(''))
      : base(type) === SIGHASH_SINGLE && nIn < tx.outs.length ? await dsha256(out(tx.outs[nIn])) : zero,
  };
}

// The legacy preimage cut at its joints. It has no fixed shape -- it is the
// whole transaction again -- so the pieces are the transaction's own, and what
// they show is the hole: there is no amount anywhere in this list.
function legacyFields(tx, nIn, code, type) {
  const one = anyone(type);
  return [
    ['nVersion', tx.version, 'the transaction’s version, four bytes'],
    ['inputs', compact(one ? 1 : tx.ins.length), one
      ? 'one — ANYONECANPAY serializes this input alone' : 'how many inputs follow'],
    ['scriptCode', withLength(code), 'this input’s script, standing where its scriptSig would; '
      + 'every other input’s is blanked to nothing'],
    ['outputs', compact(base(type) === SIGHASH_NONE ? 0
      : base(type) === SIGHASH_SINGLE ? nIn + 1 : tx.outs.length),
      base(type) === SIGHASH_NONE ? 'none — NONE commits to no output at all'
        : base(type) === SIGHASH_SINGLE ? 'up to this input’s index, with every earlier one blanked'
        : 'all of them, amounts and scripts'],
    ['nLockTime', tx.locktime, 'the earliest the transaction may be mined'],
    ['nHashType', le(type, 4), `${sighashName(type)} — which of the above the signature covers`],
    ['(no amount)', '', 'nowhere in this serialization is the value being spent — '
      + 'the hole BIP143 was written to close'],
  ];
}
